language: node_js
node_js:
    - 10
install:
    - npm ci

jobs:
    include:
        - stage: test
        - script: lerna run test
        - stage: lint
          script: lerna run lint
        - stage: typecheck
          script: lerna run typecheck

stages:
    - test
    - lint
    - typecheck
